# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  nabs-github-nuget:
    type: nuget-feed
    url: https://nuget.pkg.github.com/Net-Advantage
    username: nabs-darrel-schreyer
    password: ${{ secrets.NUGET_AUTH_TOKEN }}
  nabs-github-nuget-json:
    type: nuget-feed
    url: https://nuget.pkg.github.com/Net-Advantage/index.json
    username: nabs-darrel-schreyer
    password: ${{ secrets.NUGET_AUTH_TOKEN }}

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
     - dependency-name: "Nabs*"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "nuget dependencies"
      - "dependabot"
      - "minor"
    registries:
      - "nabs-github-nuget"
      - "nabs-github-nuget-json"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
    open-pull-requests-limit: 10
