# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  nabs-nuget:
    type: nuget-feed
    url: https://nuget.pkg.github.com/Net-Advantage/index.json  # The URL of your NuGet feed
    username: nabs-darrel-schreyer  # Username for authentication
    password: ${{secrets.NUGET_AUTH_TOKEN}}  # Reference to a GitHub secret for the password

updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    target-branch: "main"
    labels:
      - "nuget dependencies"
      - "dependabot"
      - "minor"
    registries:
      - nabs-nuget